/* Generated By:JavaCC: Do not edit this line. EXPParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EXPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int OP = 2;
  /** RegularExpression Id. */
  int REL = 3;
  /** RegularExpression Id. */
  int DELIM1 = 4;
  /** RegularExpression Id. */
  int DELIM2 = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ID>",
    "<OP>",
    "<REL>",
    "<DELIM1>",
    "<DELIM2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
